using System.Net.Sockets; using System.Text; using System.Text.Json; using Vxi.Protocol; using Vxi.Core; using Vxi.Transport.Gpib;
string configPath=Environment.GetEnvironmentVariable("VXI_CONFIG")??"/etc/vxi-controller/appsettings.json";var cfg=ConfigLoader.Load(configPath);var runner=new DriverRunner(cfg);var audit=new AuditLog(cfg.AuditLogPath);var gpib=new Dictionary<string,LinuxGpib>();foreach(var c in cfg.Connections)gpib[c.Id]=new(new(c.BoardIndex,c.PrimaryAddress,c.SecondaryAddress,c.TimeoutCode));
if(File.Exists(cfg.SocketPath))File.Delete(cfg.SocketPath);Directory.CreateDirectory(Path.GetDirectoryName(cfg.SocketPath)!);var ep=new UnixDomainSocketEndPoint(cfg.SocketPath);using var listener=new Socket(AddressFamily.Unix,SocketType.Stream,ProtocolType.Unspecified);listener.Bind(ep);listener.Listen(20);File.SetUnixFileMode(cfg.SocketPath,UnixFileMode.UserRead|UnixFileMode.UserWrite|UnixFileMode.GroupRead|UnixFileMode.GroupWrite);Console.WriteLine($"VXI broker listening on {cfg.SocketPath}");
while(true){var client=await listener.AcceptAsync();_=Task.Run(()=>Handle(client));}
async Task Handle(Socket s){await using var ns=new NetworkStream(s,true);using var r=new StreamReader(ns,Encoding.UTF8,leaveOpen:true);using var w=new StreamWriter(ns,new UTF8Encoding(false),leaveOpen:true){AutoFlush=true};try{var line=await r.ReadLineAsync();var br=JsonSerializer.Deserialize<BrokerRequest>(line!,JsonDefaults.Options)??throw new InvalidDataException("Invalid request");object data=br.Action switch{
 "status"=>new{status="ready",drivers=cfg.Drivers.Length,instruments=cfg.Instruments.Length},
 "drivers"=>cfg.Drivers.Select(x=>new{x.Id,x.Executable}),
 "devices"=>cfg.Instruments,
 "describe"=>await Describe(br),
 "operate"=>await Operate(br),
 _=>throw new ArgumentException("Unknown action")};await w.WriteLineAsync(JsonSerializer.Serialize(new BrokerResponse(true,data),JsonDefaults.Options));}
 catch(Exception ex){await audit.WriteAsync(new{type="error",message=ex.Message});await w.WriteLineAsync(JsonSerializer.Serialize(new BrokerResponse(false,Error:ex.Message),JsonDefaults.Options));}}
async Task<object> Describe(BrokerRequest br){var i=FindInstrument(br);var d=runner.Find(i.DriverId);var rr=await runner.InvokeAsync(d,new(1,Guid.NewGuid().ToString("N"),"describe",i),CancellationToken.None);if(!rr.Success)throw new InvalidOperationException(rr.Error);return rr.Operations!;}
async Task<object> Operate(BrokerRequest br){var i=FindInstrument(br);if(string.IsNullOrWhiteSpace(br.OperationId))throw new ArgumentException("operationId required");var d=runner.Find(i.DriverId);var rr=await runner.InvokeAsync(d,new(1,Guid.NewGuid().ToString("N"),"generate",i,br.OperationId,br.Parameters),CancellationToken.None);if(!rr.Success)throw new InvalidOperationException(rr.Error);var cmds=rr.Commands??[];if(cmds.Count>cfg.Security.MaxCommandsPerOperation)throw new InvalidOperationException("Too many commands");foreach(var c in cmds){if(c.Text.Contains('\n')||c.Text.Contains('\r')||c.Text.Contains(';'))throw new InvalidOperationException("Unsafe command formatting");if(!d.AllowedCategories.Contains(c.Category,StringComparer.OrdinalIgnoreCase))throw new InvalidOperationException("Command category denied");if(!d.AllowedCommandPrefixes.Any(p=>c.Text.StartsWith(p,StringComparison.OrdinalIgnoreCase)))throw new InvalidOperationException("Command prefix denied");}
 var results=new List<object>();foreach(var c in cmds){string? response=null;if(!br.DryRun){response=await gpib[i.Address.ConnectionId].ExecuteAsync(c.Text,c.ExpectsResponse,CancellationToken.None);int delay=Math.Max(c.DelayAfterMilliseconds,c.Category=="relay-switch"?cfg.Security.MinimumRelayDelayMilliseconds:0);if(delay>0)await Task.Delay(delay);}results.Add(new{c.Text,c.ExpectsResponse,c.Category,response});}await audit.WriteAsync(new{type="operation",instrument=i.Id,operation=br.OperationId,dryRun=br.DryRun,commands=cmds.Select(x=>x.Text)});return results;}
InstrumentInstance FindInstrument(BrokerRequest br)=>cfg.Instruments.SingleOrDefault(x=>x.Id==br.InstrumentId)??throw new ArgumentException("Unknown instrument");
